#!/bin/bash
echo "INFO: Running $0 in $(pwd)" >&2
valgrind \
    --log-file=ebi_solver_port-t01-valgrind-%p.log \
    --leak-check=full \
    --show-reachable=yes \
    --verbose \
    --gen-suppressions=all \
    --suppressions=../ebi_solver_port/valgrind.supp \
    ../priv/ebi_solver_port
