#!/bin/bash
# NOTE: WD will be in bio_ers and not in bio_ers/test.
valgrind \
    --log-file=ebi_solver_port-t01-valgrind-%p.log \
    --leak-check=full \
    --show-reachable=yes \
    --verbose \
    --gen-suppressions=all \
    --suppressions=../ebi_solver_port/valgrind.supp \
    ../ebi_solver_port/.libs/ebi_solver_port
